inherit_from:
  - config/rubocop/disabled.yml
AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'lib/core_ext/pkcs12.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
    - 'slide_rule.gemspec'

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
