require_relative './slide_rule/version.rb'
require_relative './slide_rule/distance_calculator.rb'
require_relative './slide_rule/distance_calculators/day_of_month.rb'
require_relative './slide_rule/distance_calculators/day_of_year.rb'
require_relative './slide_rule/distance_calculators/levenshtein.rb'
